version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  saw-products-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saw-products-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/saw_products_db"
    depends_on:
      - mongodb

volumes:
  mongo-data:
